### PR TITLE
redesigned index page and navbar

### PR DESCRIPTION
**Pull request by danieldekerlegand**
I retooled the index page and added CSS styling to the navbar. The background video is a bit hefty at 4.5 MB, but I can try to compress it down further. Let me know what you think.

### CODE REVIEW

**Comment by deanslamajr** [comment]
I like this new style a lot

**Comment by deanslamajr** [comment]
4.5 MB video is pretty large, what is the smallest you can compress this down to? Can you shorten it to just the first 5 seconds or so?

**Comment by danieldekerlegand** [comment]
Yeah, I can definitely do that tomorrow. I was also thinking about setting an image on the first frame as the jumbotron background, so that when it's loading it'll be an image instead of a black background.

**Comment by deanslamajr** [comment]
I like the look the site is taking on but I still think 1.5 MB is a lot to force on someone who casually navigates to the page. I've jumped around to a couple pages really quickly(Google.com : 330kB, reddit.com : 440kB, facebook.com : 1.8MB) and it seems that only the really content heavy pages deman that much bandwidth.

Since the video is merely a aesthetic choice, I would argue that it unnecessarily burdens the user of the site with a hefty download.

If you can get the video down in size to about half of the current size (~700kB) I could look the other way on this one ;) Otherwise, I'd vote for a png or jpeg to replace the video

**Comment by deanslamajr** [comment]
Where are the forms that the main page links to housed? I like these but who has access to them?

**Comment by deanslamajr** [comment]
This is becoming a rather large PR. In the future, try to focus a PR on single, specific features/functionality/bug fixes. This makes it easier to reason about the changes.

**Comment by danieldekerlegand** [comment]
Got it... I'll either shrink the video or replace it with a background image. I'll also limit any future pull requests to a single edit. The forms from the main page are the ones that were emailed out earlier this semester.

**Comment by deanslamajr** [comment]
My opinion on the total DL size for the video/site-as-a-whole has changed. It seems that being under 2MB is pretty damn good these days (I must be an old timer lol).

**Comment by deanslamajr** [comment]
Merged!

**Pull request merged**
